development:
  adapter: postgresql
  database: cucumber_tutorial_backend_development
  pool: 5
  timeout:

test:
  adapter: postgresql
  database: cucumber_tutorial_backend_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cucumber_tutorial_backend_production
  pool: 5
  timeout: 5000
  
